spring.application.name=chatbot-be
server.port=9090


# Database Configuration
spring.datasource.url=jdbc:postgresql://10.212.10.135:5432/hrms_db
spring.datasource.username=postgres
spring.datasource.password=Welcome@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JDBC
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10

# Optional Logging
spring.jpa.show-sql=true

# Ollama model settings
spring.ai.ollama.chat.enabled=true
#spring.ai.ollama.chat.model=gemma:2b
#spring.ai.ollama.chat.model=gemma:7b
#spring.ai.ollama.chat.model=deepseek-r1:8b
spring.ai.ollama.chat.model=llama3.2:3b
spring.ai.ollama.base-url=http://10.210.0.44:11434