#modules:
#  CUD:
#    description: "Country Underwriting Department"
#    services:
#      Country: "Country Service"
#      Membership: "Membership Subscription Service"
#      Event: "Event Service"
#      BU: "Berne Union Service"
#  BUD:
#    description: "Buyer Underwriting Department"
#    services:
#      Buyer: "Buyer Service"
#      BSAL: "BSAL Service"
#      BuyerUW: "Buyer UW Service"
#      UTIL: "Util Service"
#      IntlBank: "Intl Bank Service"
#      CRA: "CRA Service"
#      CLA: "CLA Service"
#     
#  ECIB:
#    description: "Export Credit Insurance Business"
#    services:
#      InsuranceService: "Insurance Main Service"
#      PolicyService: "Policy Handling Service"


#modules.CUD.description=Country Underwriting Department
#modules.CUD.services.Country=Country Service
#modules.CUD.services.Membership=Membership Subscription Service
#modules.CUD.services.Event=Event Service
#modules.CUD.services.BU=Berne Union Service
#
#modules.BUD.description=Buyer Underwriting Department
#modules.BUD.services.Buyer=Buyer Service
#modules.BUD.services.BSAL=BSAL Service
#modules.BUD.services.Buyeruw=Buyer UW Service
#modules.BUD.services.Util=Util Service
#modules.BUD.services.IntlBank=Intl Bank Service
#modules.BUD.services.Cra=CRA Service
#modules.BUD.services.Cla=CLA Service

modules.HRD.description=Human Resource Department
modules.HRD.services.Empattleavemgmt=Attendance and Leave Management
modules.HRD.services.Empexit=Employee Exit Management
modules.HRD.services.Empinsurance=Employee Insurance
modules.HRD.services.Emploans=Employee Loans
modules.HRD.services.Hrms=Employee Managment
modules.HRD.services.Epms=Employee Performance Management
modules.HRD.services.Ppdocf=Office Orders/ Circulars
modules.HRD.services.Hrdorgstr=Organization Structure
modules.HRD.services.Emppayfixincr=Pay Fixation and Increment
modules.HRD.services.Empreimb=Reimbursement
